
package com.lijiao.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CourseWebSerive", targetNamespace = "http://webservice.lijiao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CourseWebSerive {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.lijiao.webservice.Course
     */
    @WebMethod(operationName = "GetCourseById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCourseById", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetCourseById")
    @ResponseWrapper(localName = "GetCourseByIdResponse", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetCourseByIdResponse")
    @Action(input = "http://webservice.lijiao.com/CourseWebSerive/GetCourseByIdRequest", output = "http://webservice.lijiao.com/CourseWebSerive/GetCourseByIdResponse")
    public Course getCourseById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.lijiao.webservice.Course>
     */
    @WebMethod(operationName = "ListCourses")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListCourses", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.ListCourses")
    @ResponseWrapper(localName = "ListCoursesResponse", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.ListCoursesResponse")
    @Action(input = "http://webservice.lijiao.com/CourseWebSerive/ListCoursesRequest", output = "http://webservice.lijiao.com/CourseWebSerive/ListCoursesResponse")
    public List<Course> listCourses();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.lijiao.webservice.Course>
     */
    @WebMethod(operationName = "GetTakenCourses")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetTakenCourses", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetTakenCourses")
    @ResponseWrapper(localName = "GetTakenCoursesResponse", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetTakenCoursesResponse")
    @Action(input = "http://webservice.lijiao.com/CourseWebSerive/GetTakenCoursesRequest", output = "http://webservice.lijiao.com/CourseWebSerive/GetTakenCoursesResponse")
    public List<Course> getTakenCourses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
