
package com.lijiao.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourseWebSerive", targetNamespace = "http://webservice.lijiao.com/", wsdlLocation = "http://localhost:8080/J2EEPro/CourseWebSerive?WSDL")
public class CourseWebSerive_Service
    extends Service
{

    private final static URL COURSEWEBSERIVE_WSDL_LOCATION;
    private final static WebServiceException COURSEWEBSERIVE_EXCEPTION;
    private final static QName COURSEWEBSERIVE_QNAME = new QName("http://webservice.lijiao.com/", "CourseWebSerive");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/J2EEPro/CourseWebSerive?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSEWEBSERIVE_WSDL_LOCATION = url;
        COURSEWEBSERIVE_EXCEPTION = e;
    }

    public CourseWebSerive_Service() {
        super(__getWsdlLocation(), COURSEWEBSERIVE_QNAME);
    }

    public CourseWebSerive_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSEWEBSERIVE_QNAME, features);
    }

    public CourseWebSerive_Service(URL wsdlLocation) {
        super(wsdlLocation, COURSEWEBSERIVE_QNAME);
    }

    public CourseWebSerive_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSEWEBSERIVE_QNAME, features);
    }

    public CourseWebSerive_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseWebSerive_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourseWebSerive
     */
    @WebEndpoint(name = "CourseWebSerivePort")
    public CourseWebSerive getCourseWebSerivePort() {
        return super.getPort(new QName("http://webservice.lijiao.com/", "CourseWebSerivePort"), CourseWebSerive.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseWebSerive
     */
    @WebEndpoint(name = "CourseWebSerivePort")
    public CourseWebSerive getCourseWebSerivePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.lijiao.com/", "CourseWebSerivePort"), CourseWebSerive.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSEWEBSERIVE_EXCEPTION!= null) {
            throw COURSEWEBSERIVE_EXCEPTION;
        }
        return COURSEWEBSERIVE_WSDL_LOCATION;
    }

}
