
package com.lijiao.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuizWebService", targetNamespace = "http://webservice.lijiao.com/", wsdlLocation = "http://localhost:8080/J2EEPro/QuizWebService?WSDL")
public class QuizWebService_Service
    extends Service
{

    private final static URL QUIZWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUIZWEBSERVICE_EXCEPTION;
    private final static QName QUIZWEBSERVICE_QNAME = new QName("http://webservice.lijiao.com/", "QuizWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/J2EEPro/QuizWebService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUIZWEBSERVICE_WSDL_LOCATION = url;
        QUIZWEBSERVICE_EXCEPTION = e;
    }

    public QuizWebService_Service() {
        super(__getWsdlLocation(), QUIZWEBSERVICE_QNAME);
    }

    public QuizWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUIZWEBSERVICE_QNAME, features);
    }

    public QuizWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, QUIZWEBSERVICE_QNAME);
    }

    public QuizWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUIZWEBSERVICE_QNAME, features);
    }

    public QuizWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuizWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuizWebService
     */
    @WebEndpoint(name = "QuizWebServicePort")
    public QuizWebService getQuizWebServicePort() {
        return super.getPort(new QName("http://webservice.lijiao.com/", "QuizWebServicePort"), QuizWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuizWebService
     */
    @WebEndpoint(name = "QuizWebServicePort")
    public QuizWebService getQuizWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.lijiao.com/", "QuizWebServicePort"), QuizWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUIZWEBSERVICE_EXCEPTION!= null) {
            throw QUIZWEBSERVICE_EXCEPTION;
        }
        return QUIZWEBSERVICE_WSDL_LOCATION;
    }

}
