
package com.lijiao.webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QuizWebService", targetNamespace = "http://webservice.lijiao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuizWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Quiz")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Quiz", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.Quiz")
    @ResponseWrapper(localName = "QuizResponse", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.QuizResponse")
    @Action(input = "http://webservice.lijiao.com/QuizWebService/QuizRequest", output = "http://webservice.lijiao.com/QuizWebService/QuizResponse")
    public String quiz();

}
