
package com.lijiao.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "http://webservice.lijiao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUserById2")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetUserById2", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetUserById2")
    @ResponseWrapper(localName = "GetUserById2Response", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetUserById2Response")
    @Action(input = "http://webservice.lijiao.com/UserWebService/GetUserById2Request", output = "http://webservice.lijiao.com/UserWebService/GetUserById2Response")
    public String getUserById2(
        @WebParam(name = "UserId", targetNamespace = "")
        Long userId);

    /**
     * 
     * @param userId
     * @return
     *     returns com.lijiao.webservice.User
     */
    @WebMethod(operationName = "GetUserById")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetUserById", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetUserById")
    @ResponseWrapper(localName = "GetUserByIdResponse", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetUserByIdResponse")
    @Action(input = "http://webservice.lijiao.com/UserWebService/GetUserByIdRequest", output = "http://webservice.lijiao.com/UserWebService/GetUserByIdResponse")
    public User getUserById(
        @WebParam(name = "UserId", targetNamespace = "")
        Long userId);

    /**
     * 
     * @return
     *     returns java.util.List<com.lijiao.webservice.User>
     */
    @WebMethod(operationName = "ShowAllUsers")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ShowAllUsers", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.ShowAllUsers")
    @ResponseWrapper(localName = "ShowAllUsersResponse", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.ShowAllUsersResponse")
    @Action(input = "http://webservice.lijiao.com/UserWebService/ShowAllUsersRequest", output = "http://webservice.lijiao.com/UserWebService/ShowAllUsersResponse")
    public List<User> showAllUsers();

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetAuthenticate")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAuthenticate", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetAuthenticate")
    @ResponseWrapper(localName = "GetAuthenticateResponse", targetNamespace = "http://webservice.lijiao.com/", className = "com.lijiao.webservice.GetAuthenticateResponse")
    @Action(input = "http://webservice.lijiao.com/UserWebService/GetAuthenticateRequest", output = "http://webservice.lijiao.com/UserWebService/GetAuthenticateResponse")
    public int getAuthenticate(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
